project_name: netcon-cli
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - id: build-linux
    main: ./cmd/netcon
    binary: netcon
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/janog-netcon/netcon-cli/pkg/version.Version={{.Version}}
      - -X github.com/janog-netcon/netcon-cli/pkg/version.Revision={{.ShortCommit}}
    goos:
      - linux
    goarch:
      - amd64
  - id: build-darwin
    main: ./cmd/netcon
    binary: netcon
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - darwin
    goarch:
      - amd64
archives:
  - id: netcon-cli-archive
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64

dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - netcon
    builds:
      - build-linux
    dockerfile: ./Dockerfile
    image_templates:
      - hnron-public.sakuracr.jp/netcon-cli:{{.Version}}
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: true

# publish
release:
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
