project_name: netcon-cli
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - id: build-linux
    main: ./cmd/netcon
    binary: netcon
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/janog-netcon/netcon-cli/pkg/version.Version={{.Version}}
      - -X github.com/janog-netcon/netcon-cli/pkg/version.Revision={{.ShortCommit}}
    goos:
      - linux
    goarch:
      - amd64
  - id: build-darwin
    main: ./cmd/netcon
    binary: netcon
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - darwin
    goarch:
      - amd64
archives:
  - id: netcon-cli-archive
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64

# publish
release:
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
