project_name: netcon-cli
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - id: build-linux
    main: ./cmd/netcon
    binary: netcon
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
  - id: build-darwin
    main: ./cmd/netcon
    binary: netcon
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - darwin
    goarch:
      - amd64
archives:
  - id: netcon-cli-archive
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

# publish
release:
  disable: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
