name: release
on:
  push:
    branches:
    - '*'
    tags:
    #- "v[0-9]+.[0-9]+.[0-9]+"
    - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}


      - name: Push to sakuracr
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.SAKURACR_USERNAME }}
          password: ${{ secrets.SAKURACR_PASSWORD }}
          registry: hnron-public.sakuracr.jp
          repository: netcon
          tag_with_ref: true

      #- name: Log into registry
      #  run: echo "${{ secrets.SAKURACR_PASSWORD }}" | docker login $REPOSITORY_NAME -u ${{ secrets.SAKURACR_USERNAME }} --password-stdin
      #- name: Push image
      #  run: |
      #    IMAGE_ID=$REPOSITORY_NAME/$IMAGE_NAME

      #    # Change all uppercase to lowercase
      #    IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

      #    # Strip git ref prefix from version
      #    VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

      #    # Strip "v" prefix from tag name
      #    [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

      #    # Use Docker `latest` tag convention
      #    [ "$VERSION" == "main" ] && VERSION=latest

      #    echo IMAGE_ID=$IMAGE_ID
      #    echo VERSION=$VERSION

      #    #docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
      #    docker push $IMAGE_ID:$VERSION

